version: '3.2'

services:
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1qaz
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=1qaz
    ports:
      - "7000:80"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - HOST_IP_ADDRESS=http://backend:80
    ports:
      - "80:80"
